version: '3.5'

services:
  database:
    image: postgres:14-alpine 
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django   
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - back   
    
  backend:
    build:
      context: ./lib_catalog
      dockerfile: Dockerfile_back
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./lib_catalog:/app
    
    ports: 
      - 8000:8000
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
    depends_on: 
      - database
      - frontend
    restart: always
    networks:
      - front
      - back

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_web
    restart: always
    volumes: 
      - ./frontend:/app
    ports: 
      - 3000:80
    networks:
      - front
    


networks:
  back:
    driver: bridge
    ipam:
      config: 
        - subnet: 10.178.236.0/24
          gateway: 10.178.236.1
          aux_addresses: 
            database: 10.178.236.2
            backend: 10.178.236.3
  front: 
    driver: bridge
    ipam:
      config: 
        - subnet: 10.178.237.0/24
          gateway: 10.178.237.1
          aux_addresses: 
            frontend: 10.178.237.2
   
